name: Deploy IMS Frontend to Vercel

on:
  push:
    branches:
      - "**"

jobs:
  changes:
    name: Check code changes
    runs-on: ubuntu-latest
    outputs:
      imsfe: ${{ steps.filter.outputs.imsfe }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for code changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            imsfe:
              - 'frontend/**'

  imsfe:
    name: Deploy IMS Frontend to Vercel
    runs-on: ubuntu-latest
    needs: changes
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Run Next.js Build
        run: npm run build

      - name: Install Vercel CLI
        if: github.ref == 'refs/heads/main'
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: github.ref == 'refs/heads/main'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: github.ref == 'refs/heads/main'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Set Vercel Alias
        if: github.ref == 'refs/heads/main'
        run: vercel alias set imsp.vercel.app --token=${{ secrets.VERCEL_TOKEN }}
